hubert_arm:
  kinematics_solver: hubert_hubert_arm/IKFastKinematicsPlugin #kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  position_only_ik: True